#!/bin/bash
 
USER=cleong
MACHINE=MACHINE_NAME
SERVER_DATA_DIR=YOUR_PATH_TO_SERVER_DATA
DOCKER_DATA_DIR=YOUR_PATH_TO_DOCKER_DATA
VIDEO_DATA_DIR=video
 
mkdir -p $DOCKER_DATA_DIR
 
sshfs -o idmap=user $USER@$MACHINE.XXX.XX.ORG:$SERVER_DATA_DIR $DOCKER_DATA_DIR
 
./FeatureExtraction -q -f $DOCKER_DATA_DIR/$VIDEO_DATA_DIR/test.mp4 -out_dir $DOCKER_DATA_DIR/$VIDEO_DATA_DIR -of test.features

